// In JavaScript, define a function `group` which accepts an array, `collection`, as the first parameter and a function, `grouper`, as the second parameter. `group` should return an object composed of keys generated by running each element of `collection` through `grouper`. The value of each key should be an array of elements responsible for generating that key.

// For example:

// group([6.5, 4.2, 6.3], Math.floor);
// { '4': [4.2], '6': [6.5, 6.3] }
const group = (collection, grouper) => {
  const result = {};
  collection.reduce((acc, cv) => {
    if (result[grouper(cv)]) {
      result[grouper(cv)].push(cv);
    } else {
      result[grouper(cv)] = [cv];
    }
  }, result);
  return result;
};
console.log(group([6.5, 4.2, 6.3], Math.floor));
